import React,{useEffect,useState}from"react";import{createRoot}from"react-dom/client";import{io}from"socket.io-client";import{Heart,MessageCircle,Send,Image as ImageIcon,LogIn,UserPlus,LogOut,Camera}from"lucide-react";import"./styles.css";
const API=import.meta.env.VITE_API_URL||"http://localhost:4000";
const api=async(path,opt={})=>{const token=localStorage.getItem("qf_token");const headers=opt.body instanceof FormData?{}:{"Content-Type":"application/json"};if(token)headers.Authorization="Bearer "+token;const r=await fetch(API+path,{...opt,headers:{...headers,...(opt.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"حدث خطأ");return d};
function Auth({onLogin}){const[mode,setMode]=useState("login"),[form,setForm]=useState({name:"",email:"",password:""}),[err,setErr]=useState("");const submit=async e=>{e.preventDefault();try{const d=await api("/api/auth/"+mode,{method:"POST",body:JSON.stringify(form)});localStorage.setItem("qf_token",d.token);onLogin(d.user)}catch(x){setErr(x.message)}};return <div className="auth"><div className="authbox"><div className="logo">QF</div><h1>Queen Fatima</h1><p>منصة اجتماعية حقيقية</p><form onSubmit={submit}>{mode==="register"&&<input placeholder="الاسم الكامل" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/>}<input type="email" placeholder="البريد الإلكتروني" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} required/><input type="password" placeholder="كلمة المرور" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} required minLength="6"/>{err&&<div className="error">{err}</div>}<button>{mode==="login"?<><LogIn/> تسجيل الدخول</>:<><UserPlus/> إنشاء حساب</>}</button></form><a onClick={()=>{setMode(mode==="login"?"register":"login");setErr("")}}>{mode==="login"?"ليس لديك حساب؟ إنشاء حساب":"لديك حساب؟ تسجيل الدخول"}</a></div></div>}
function App(){const[user,setUser]=useState(null),[posts,setPosts]=useState([]),[text,setText]=useState(""),[file,setFile]=useState(null),[comments,setComments]=useState({}),[messages,setMessages]=useState([]),[to,setTo]=useState(""),[msg,setMsg]=useState(""),[socket,setSocket]=useState(null);
useEffect(()=>{api("/api/me").then(d=>setUser(d.user)).catch(()=>{})},[]);
useEffect(()=>{if(!user)return;api("/api/posts").then(d=>setPosts(d.posts));const s=io(API,{auth:{token:localStorage.getItem("qf_token")}});s.on("message:new",m=>setMessages(x=>[...x,m]));setSocket(s);return()=>s.close()},[user]);
if(!user)return <Auth onLogin={setUser}/>;
const publish=async()=>{if(!text.trim()&&!file)return;const fd=new FormData();fd.append("text",text);if(file)fd.append("image",file);const d=await api("/api/posts",{method:"POST",body:fd});setPosts([d.post,...posts]);setText("");setFile(null)};
const like=async id=>{const d=await api("/api/posts/"+id+"/like",{method:"POST"});setPosts(posts.map(p=>p.id===id?{...p,likes:d.likes,liked:d.liked}:p))};
const send=()=>{if(!to||!msg.trim()||!socket)return;socket.emit("message:send",{to:Number(to),body:msg});setMsg("")};
return <div className="app"><header><div className="brand"><span>QF</span><b>Queen Fatima</b></div><div className="user"><img src={user.avatar||"https://i.pravatar.cc/80?u="+user.id}/><b>{user.name}</b><button onClick={()=>{localStorage.removeItem("qf_token");location.reload()}}><LogOut/></button></div></header><main>
<section><div className="composer"><div className="row"><img src={user.avatar||"https://i.pravatar.cc/80?u="+user.id}/><input value={text} onChange={e=>setText(e.target.value)} placeholder="بماذا تفكر؟"/></div><div className="composerbar"><label><ImageIcon/> صورة<input type="file" accept="image/*" onChange={e=>setFile(e.target.files[0])}/></label>{file&&<small>{file.name}</small>}<button onClick={publish}>نشر <Send/></button></div></div>
{posts.map(p=><article className="post" key={p.id}><div className="posthead"><img src={p.author.avatar||"https://i.pravatar.cc/80?u="+p.author.id}/><div><b>{p.author.name}</b><small>{new Date(p.created_at).toLocaleString("ar")}</small></div></div><p>{p.text}</p>{p.image_url&&<img className="postimg" src={API+p.image_url}/>}<div className="stats">{p.likes} إعجاب · {p.comments_count} تعليق</div><div className="actions"><button onClick={()=>like(p.id)} className={p.liked?"liked":""}><Heart/> إعجاب</button><button><MessageCircle/> تعليق</button></div><CommentBox id={p.id} comments={comments[p.id]||[]} setComments={setComments}/></article>)}</section>
<aside><div className="card"><h3>حسابك</h3><p>{user.email}</p><small>المعرّف: {user.id}</small></div><div className="card"><h3>رسائل مباشرة</h3><input placeholder="معرّف المستخدم" value={to} onChange={e=>setTo(e.target.value)}/><div className="chat">{messages.filter(m=>m.sender_id===Number(to)||m.receiver_id===Number(to)).map((m,i)=><p key={i}><b>{m.sender_name||m.sender_id}:</b> {m.body}</p>)}</div><div className="sendrow"><input value={msg} onChange={e=>setMsg(e.target.value)} onKeyDown={e=>e.key==="Enter"&&send()} placeholder="اكتب رسالة..."/><button onClick={send}><Send/></button></div></div></aside>
</main></div>}
function CommentBox({id,comments,setComments}){const[v,setV]=useState(""),load=async()=>{const d=await api("/api/posts/"+id+"/comments");setComments(x=>({...x,[id]:d.comments}))};useEffect(()=>{load()},[]);const add=async()=>{if(!v.trim())return;await api("/api/posts/"+id+"/comments",{method:"POST",body:JSON.stringify({body:v})});setV("");load()};return <div className="comments">{comments.map(c=><div key={c.id}><b>{c.author.name}</b> {c.body}</div>)}<div className="commentinput"><input value={v} onChange={e=>setV(e.target.value)} onKeyDown={e=>e.key==="Enter"&&add()} placeholder="اكتب تعليقاً..."/><button onClick={add}><Send/></button></div></div>}
createRoot(document.getElementById("root")).render(<App/>);